### ISSUE TITLE
Landing Page Hazırlanması

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-ui-ux#1]
Kendi tanıtımızı yapmamız ve kullanıcının her şeye erişebilmesi için Landing Page hazırlanması gerekiyor.

### İçerik
- **Biz kimiz ne yapıyoruz?**
> Afet Yönetim Sistemi, https://github.com/acikkaynak/afet-org/discussions/35 alanındaki fikri gönüllü olarak hayata geçirmek için katkı sağlayan bir topluluktur.

Afet Yönetim Sistemi, Bir kuruma bağlı olan gönüllü kişilerin afet bölgesine kişi ve/veya alet edevat taşıma sürecinin gerçekleştirilmesi ve bu süreçte kişilerin güvenliğinin sağlanması, kurumun koordinasyonunun sağlanması, doğru envanterin doğru konuma gönderilmesini hedefliyoruz. Afet sonrası yardımların güvenli ve sağlıklı bir şekilde ulaşması için teknik çözümler üretiyoruz.

Detaylı bilgi için [Discord](https://discord.gg/3ShTaTJr4f) kanalımıza dahil olabilir, ilgili repositoryleri inceleyebilir, gönüllü kişilerle iletişime geçerek bize destek olabilirsin.

- **Hangi teknolojileri kullanıyoruz?**
> **Teknik Gereksinim**
Back-End: Java17, Spring Boot 3, Docker, MySQL
Front-End: React.js, TypeScript
iOS: Swift
Android: Kotlin
DevOps: Amazon Web Services, Terminal Skills
UI/UX Design: Figma
Product: Github Project
Test: API & UI Test Automation, Manuel Testing
Moderating: Orientation, Organization Bots
- **Sosyal medya hesaplarımız?**
> GitHub, Discord sayfalarına erişim gerektiği.
GitHub : https://github.com/afet-yonetim-sistemi
Discord : https://discord.gg/3ShTaTJr4f

--- 

> Buradaki yazılar revize edilebilir.

**Comment by busraselimoglu** [comment]
https://www.figma.com/file/BEl5DcvE3GORgC903FWESA/ays-landingpage?type=design&node-id=0-1&mode=design
