### ISSUE TITLE
Map Üzerindeki Pin'in Güncellenmesi

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-ui-ux#2]

**Comment by agitrubard** [comment]
@TolgaTaner bu issue ile ilgili detayları ekleyebilir misin?

**Comment by TolgaTaner** [comment]
@agitrubard detayları Büşra not almış olmalı. Öyle değilse tekrardan konuşalım olmadı.

**Comment by agitrubard** [comment]
@busraselimoglu Selamlar,
Bu konuyla ilgili notlar almış mıydın? Almışsan buraya da yansıtabilir misin?
