### ISSUE TITLE
Mobil | Kullanıcı Giriş Ekranı Tasarımının Yapılması

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-ui-ux#3]
Bu issue ile birlikte kullanıcı giriş ekranının tasarımı yapılmalıdır.

---

### TR
- [x] Component'in içerisinde en üstte ve ortalı olacak şekilde Afet Yönetim Sistemi Logosunun eklenmesi gerekmektedir.
https://i.hizliresim.com/k4huqn1.png
- [x] Textboxların üst kısmında aşağıdaki görselde olduğu gibi `Hoş Geldiniz` başlığı ve bu başlığın altına `Lütfen Kullanıcı Adınızı ve Şifrenizi giriniz.` yazmalı.
![image](https://github.com/afet-yonetim-sistemi/ays-ui-ux/assets/61833677/2e7081a9-03eb-412e-9ebf-1b9673cec1bc)
- [x] Kullanıcı Adı ve Şifre için iki ayrı textbox olmalı. Var olan figma tasarımında bulunan `Kullanıcı adı veya E-posta` yazısı yerine sadece `Kullanıcı Adı` yazmalı.
- [x] `GİRİŞ YAP` yazısı yerine `OTURUM AÇ` yazısı olmalı.
![image](https://github.com/afet-yonetim-sistemi/ays-ui-ux/assets/61833677/85f4e340-0b36-48ce-9407-dce87fd20539)
- [x] Genel ekran tasarımı Kurum tarafındaki tasarıma benzetilmeli.

### EN
- [x] Component'in içerisinde en üstte ve ortalı olacak şekilde Afet Yönetim Sistemi Logosunun eklenmesi gerekmektedir.
https://i.hizliresim.com/k4huqn1.png
- [x] Textboxların üst kısmında aşağıdaki görselde olduğu gibi `Welcome` başlığı ve bu başlığın altına `Please enter your Username and Password.` yazmalı.
![image](https://github.com/afet-yonetim-sistemi/ays-ui-ux/assets/61833677/ce599585-5740-4da0-84d7-173d9a4e4e23)
- [x] Kullanıcı Adı ve Şifre için iki ayrı textbox olmalı. `Username` ve `Password` başlıklarına sahip olmalı.
- [x] Aksiyon butonunda `LOGIN` yazısı olmalı.
![image](https://github.com/afet-yonetim-sistemi/ays-ui-ux/assets/61833677/85f4e340-0b36-48ce-9407-dce87fd20539)
- [x] Genel ekran tasarımı Kurum tarafındaki tasarıma benzetilmeli.

---

### Mobil Uygulama Figma Tasarımları;
https://www.figma.com/file/VgGo5zOJXI5Uzq81R4q43K/AYS-Mobil?type=design&node-id=2-1292&mode=design

**Comment by agitrubard** [comment]
@busraselimoglu Selamlar,
Institution tarafındaki son düzenlemeler tamamlandı, mobil tarafta da aşağıdaki örnek ekrandaki gibi olması beklenmekte;

### TR
![image](https://github.com/afet-yonetim-sistemi/ays-ui-ux/assets/61833677/2239c41c-746e-4cbc-8bde-4729b9cbc8f9)

### EN
![image](https://github.com/afet-yonetim-sistemi/ays-ui-ux/assets/61833677/fc17a1f6-1561-481b-8cbe-c2e74d47997d)

**Comment by busraselimoglu** [comment]
Taslak Tasarım: https://www.figma.com/file/qLaPWunhxXq4LVI3Fj91pw/ays-mobil-design-1?type=design&node-id=0%3A1&mode=design&t=OrFv1C8tpRnXjicr-1

Genel Tasarım: https://www.figma.com/file/jUl6RLzaN996HsYcZXpdfr/ays-mobil-design-(finished)?type=design&node-id=0%3A1&mode=design&t=d2dHAxMmAuTIyMfn-1
