### ISSUE TITLE
Mobil | Kullanıcı Sözleşmesi Onay Ekranı Tasarımının Yapılması

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-ui-ux#4]
Bu issue ile birlikte kullanıcı giriş ekranından sonra gelen kullanıcı sözleşmesi onay ekranının tasarımı yapılmalıdır.

---

### TR
- [x] Component'in içerisinde en üstte ve ortalı olacak şekilde buton rengiyle aynı olan bir doküman ikonu eklenmelidir.
- [x] `Uygulamayı kullanmaya devam etmek için Kullanıcı Sözleşmesini okuyup, onaylamanız gerekmektedir.` yazısı olmalıdır. Bu yazı belirgin bir yazı olmalıdır ve buton rengiyle aynı olmalıdır.
- [x] Checkbox yerine doğrudan butona aksiyon aldırabilir miyiz? Bu konu tartışılmalı.
   - [x]  Eğer checkbox olacak ise yazı olarak `Kullanıcı Sözleşmesini okudum ve onaylıyorum.` yazmalıdır. Ve bu yazı daha belirgin bir yazı olmalıdır.
   - [x] Eğer checkbox olmayacak ise `Kullanıcı Sözleşmesini okuduysanız 'ONAYLA' butonuna tıklayabilirsiniz.` gibi bir yazı ekleyebiliriz. Bu senaryoda `DEVAM` butonu yerine `ONAYLIYORUM` gibi bir buton olabilir.
- [x] Genel ekran tasarımı Kurum tarafındaki tasarıma benzetilmeli.

### EN
- [x] Component'in içerisinde en üstte ve ortalı olacak şekilde buton rengiyle aynı olan bir doküman ikonu eklenmelidir.
- [x] `To continue using the application, you need to read and accept the User Agreement.` yazısı olmalıdır. Bu yazı belirgin bir yazı olmalıdır ve buton rengiyle aynı olmalıdır.
- [x] Checkbox yerine doğrudan butona aksiyon aldırabilir miyiz? Bu konu tartışılmalı.
   - [x]  Eğer checkbox olacak ise yazı olarak `I have read and agree to the User Agreement.` yazmalıdır. Ve bu yazı daha belirgin bir yazı olmalıdır.
   - [x] Eğer checkbox olmayacak ise `"If you have read the User Agreement, you can click the 'I AGREE' button.` gibi bir yazı ekleyebiliriz. Bu senaryoda `CONTINUE` butonu yerine `I AGREE` gibi bir buton olabilir.
- [x] Genel ekran tasarımı Kurum tarafındaki tasarıma benzetilmeli.

---

### Mobil Uygulama Figma Tasarımları;
https://www.figma.com/file/VgGo5zOJXI5Uzq81R4q43K/AYS-Mobil?type=design&node-id=2-1292&mode=design

**Comment by busraselimoglu** [comment]
Taslak Tasarım: https://www.figma.com/file/qLaPWunhxXq4LVI3Fj91pw/ays-mobil-design-1?type=design&node-id=0%3A1&mode=design&t=OrFv1C8tpRnXjicr-1

Genel Tasarım: https://www.figma.com/file/jUl6RLzaN996HsYcZXpdfr/ays-mobil-design-(finished)?type=design&node-id=0%3A1&mode=design&t=d2dHAxMmAuTIyMfn-1

**Comment by rasitcolakel** [comment]
Kullanıcının ekrandan çıkabilmek için geri butonu ve/veya reddediyorum butonlarının eklenmesi iyi olabilir.

Ek olarak; `Okudum` yerine onayladığını belirtmek için `Okudum, onaylıyorum` olarak değiştirebiliriz
