### ISSUE TITLE
Mobil | Konum Paylaşım İzin Ekranı Tasarımının Yapılması

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-ui-ux#5]
Bu issue ile birlikte kullanıcı sözleşmesi onay ekranından sonra gelen konum paylaşım izin ekranının tasarımı yapılmalıdır.

---

### TR
- [x] Component'in içerisinde en üstte ve ortalı olacak şekilde buton rengiyle aynı olan bir konum ikonu eklenmelidir.
- [x] `Haritayı görüntüleyebilmek ve uygulama içi aksiyonları alabilmek için konum bilgilerinizi paylaşmanız gerekmektedir. Konum bilgilerinizi paylaşmak için 'PAYLAŞ' butonuna tıklayınız.` yazısı olmalıdır. Bu yazı belirgin bir yazı olmalıdır ve buton rengiyle aynı olmalıdır.
- [x] Aksiyon butonunda `DEVAM` yazısı yerine `PAYLAŞ` yazısı olmalı.
- [x] Genel ekran tasarımı Kurum tarafındaki tasarıma benzetilmeli.

### EN
- [x] Component'in içerisinde en üstte ve ortalı olacak şekilde buton rengiyle aynı olan bir konum ikonu eklenmelidir.
- [x] `To view the map and take in-app actions, you need to share your location information. Click the 'SHARE' button to share your location information.` yazısı olmalıdır. Bu yazı belirgin bir yazı olmalıdır ve buton rengiyle aynı olmalıdır.
- [x] Aksiyon butonunda `CONTINUE` yazısı yerine `SHARE` yazısı olmalı.
- [x] Genel ekran tasarımı Kurum tarafındaki tasarıma benzetilmeli.

---

### Mobil Uygulama Figma Tasarımları;
https://www.figma.com/file/VgGo5zOJXI5Uzq81R4q43K/AYS-Mobil?type=design&node-id=2-1292&mode=design

**Comment by busraselimoglu** [comment]
Taslak Tasarım: https://www.figma.com/file/qLaPWunhxXq4LVI3Fj91pw/ays-mobil-design-1?type=design&node-id=0%3A1&mode=design&t=OrFv1C8tpRnXjicr-1

Genel Tasarım: https://www.figma.com/file/jUl6RLzaN996HsYcZXpdfr/ays-mobil-design-(finished)?type=design&node-id=0%3A1&mode=design&t=d2dHAxMmAuTIyMfn-1
