### ISSUE TITLE
Mobil | Ana Ekran Tasarımının Yapılması

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-ui-ux#6]
Bu issue ile birlikte kullanıcı ana ekran tasarımı yapılmalıdır.

---

### TR
- [x] Ana ekran harita olarak kullanıcının kendi konumu ile birlikte açılmalıdır.
- [x] Haritanın sol üst köşesinde menü iconu olmalı ve açılabilir bir menüye gidilmelidir. Buradaki ikon daire şeklinde değil kurum tarafındaki ekranlarda var olan butonlardaki gibi dikdörtgen ve köşeleri oval şeklinde olmalıdır. (Bu issue ile birlikte sadece menü ikonu eklenecektir. Diğer kısımlar farklı issue'larda ele alınacak.)
- [x] Sağ en üst köşede kendi kişisel bilgilerini görebileceği bir ikon olmalı ve o kısımda kendi kişisel bilgilerine hızlıca erişebilmelidir. Buradaki ikon daire şeklinde değil kurum tarafındaki ekranlarda var olan butonlardaki gibi dikdörtgen ve köşeleri oval şeklinde olmalıdır. (Bu issue ile birlikte sadece menü ikonu eklenecektir. Diğer kısımlar farklı issue'larda ele alınacak.)
- [x] Uygulamanın ana ekranında örnek tasarımda olan `Home` veya `Work` gibi ikonlara benzer olacak şekilde sayfanın en altında ve ortada olacak şekilde sadece 1 ikon olacak şekilde bir tasarım yapılmalı. Destek Statüsünü güncellemek için kullanacağı aksiyon butonu olmalıdır. Buradaki ikon daire şeklinde değil kurum tarafındaki ekranlarda var olan butonlardaki gibi dikdörtgen ve köşeleri oval şeklinde olmalıdır. İlgili butonun altında `Destek Statüsünü Güncelle` yazmalı.
- [x] Sayfanın en altında ise aşağıdaki kısımda olduğu gibi bir arama butonu olmalı. Bu arama butonuyla birlikte kullanıcı ihtiyaç araması yapabiliyor olmalı. İlgili buton içerisinde `ATAMA ARA` yazmalı.
   - [x] Kullanıcının statüsü atama aramaya uygun olmaması durumu için bu ekranın aynısından bir ekran daha oluşturulmalı ve burada arama butonu olmamalı, sadece statü butonu olmalı.
![Screenshot 2023-10-06 at 12 37 26 PM](https://github.com/afet-yonetim-sistemi/ays-ui-ux/assets/61833677/4790f1af-28eb-4be6-a9f9-0efe96565c19)
   - [x] Atama arama sürecinde herhangi bir atama bulunamadığı senaryoda bir uyarı ekranı oluşturularak bir uyarı verilmesi gerekmektedir. `Uygun bir atama bulanamadı.` yazısı ile birlikte bir uyarı ekranı gösterilmelidir.
- [x] Genel ekran tasarımı Kurum tarafındaki tasarıma benzetilmeli.

### EN
- [x] Ana ekran harita olarak kullanıcının kendi konumu ile birlikte açılmalıdır.
- [x] Haritanın sol üst köşesinde menü iconu olmalı ve açılabilir bir menüye gidilmelidir. Buradaki ikon daire şeklinde değil kurum tarafındaki ekranlarda var olan butonlardaki gibi dikdörtgen ve köşeleri oval şeklinde olmalıdır. (Bu issue ile birlikte sadece menü ikonu eklenecektir. Diğer kısımlar farklı issue'larda ele alınacak.)
- [x] Sağ en üst köşede kendi kişisel bilgilerini görebileceği bir ikon olmalı ve o kısımda kendi kişisel bilgilerine hızlıca erişebilmelidir. Buradaki ikon daire şeklinde değil kurum tarafındaki ekranlarda var olan butonlardaki gibi dikdörtgen ve köşeleri oval şeklinde olmalıdır. (Bu issue ile birlikte sadece menü ikonu eklenecektir. Diğer kısımlar farklı issue'larda ele alınacak.)
- [x] Uygulamanın ana ekranında örnek tasarımda olan `Home` veya `Work` gibi ikonlara benzer olacak şekilde sayfanın en altında ve ortada olacak şekilde sadece 1 ikon olacak şekilde bir tasarım yapılmalı. Destek Statüsünü güncellemek için kullanacağı aksiyon butonu olmalıdır. Buradaki ikon daire şeklinde değil kurum tarafındaki ekranlarda var olan butonlardaki gibi dikdörtgen ve köşeleri oval şeklinde olmalıdır. İlgili butonun altında `Update Support Status` yazmalı.
- [x] Sayfanın en altında ise aşağıdaki kısımda olduğu gibi bir arama butonu olmalı. Bu arama butonuyla birlikte kullanıcı ihtiyaç araması yapabiliyor olmalı. İlgili buton içerisinde `SEARCH ASSIGNMENT` yazmalı.
   - [x] Kullanıcının statüsü atama aramaya uygun olmaması durumu için bu ekranın aynısından bir ekran daha oluşturulmalı ve burada arama butonu olmamalı, sadece statü butonu olmalı.
![Screenshot 2023-10-06 at 12 37 26 PM](https://github.com/afet-yonetim-sistemi/ays-ui-ux/assets/61833677/4790f1af-28eb-4be6-a9f9-0efe96565c19)
   - [x] Atama arama sürecinde herhangi bir atama bulunamadığı senaryoda bir uyarı ekranı oluşturularak bir uyarı verilmesi gerekmektedir. `An appropriate assignment couldn't be found.` yazısı ile birlikte bir uyarı ekranı gösterilmelidir.
- [x] Genel ekran tasarımı Kurum tarafındaki tasarıma benzetilmeli.

---

## Örnek Ekranlar;
![image](https://github.com/afet-yonetim-sistemi/ays-ui-ux/assets/61833677/eab08af5-af16-4c2d-bfc9-362f07ce9f3c)
![image](https://github.com/afet-yonetim-sistemi/ays-ui-ux/assets/61833677/7c9b5cf6-6501-4485-bd68-bdcc6718adca)

---

### Mobil Uygulama Figma Tasarımları;
https://www.figma.com/file/VgGo5zOJXI5Uzq81R4q43K/AYS-Mobil?type=design&node-id=2-1292&mode=design

**Comment by busraselimoglu** [comment]
Taslak Tasarım: https://www.figma.com/file/OarumtKqDTYusOuw1oqIiW/ays-mobil-design-2?type=design&node-id=13%3A221&mode=design&t=ELPThtgoTovp8Slm-1

Genel Tasarım: https://www.figma.com/file/jUl6RLzaN996HsYcZXpdfr/ays-mobil-design-(finished)?type=design&node-id=0%3A1&mode=design&t=d2dHAxMmAuTIyMfn-1
