### ISSUE TITLE
Mobil | Atama Onay Ekran Tasarımının Yapılması

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-ui-ux#7]
Bu issue ile birlikte kullanıcı atama arama yaptıktan sonra gelecek olan atama onay ekran tasarımı yapılmalıdır.

---

### TR
- [x] Ana ekran kapanmayacak ve onay kısmı görünecek şekilde bir tasarım olmalı. 
- [x] Kullanıcının konumu ve atamanın konumu arasında bir yol çizilerek ilgili konum ve uzaklığını ön izlemesi görüntülenmeli.
- [x] Açılan pencere içerisinde atamaya ait açıklama, kilometre ve uzaklık bilgisi yer almalıdır.
- [x] Örnek ekranda en üstte bulunan ikonlar olmamalı. Çünkü kullanıcı onayla veya reddet aksiyonlarından birini almak durumunda. Text olarak butonlarda `Onayla` ve `Reddet` yazmalı.
- [x] Açılır pencerede kullanıcının hiçbir aksiyon almamasına karşın iptal etmek için bir sayaç olmalı, ilgili sayaç 15 saniyelik bir sayaç olmalıdır. 15-10 saniye arası yeşil 10-5 saniye arası sarı ve 5-0 saniye arası kırmızı olarak görünmelidir. Teknik olarak mobil tarafta renk geçişi sağlanabiliyorsa renk geçişi şeklinde de olabilir.
![image](https://github.com/afet-yonetim-sistemi/ays-ui-ux/assets/61833677/a02fd948-686f-4bd4-90df-bae2d87d24b8)
- [x] Genel ekran tasarımı Kurum tarafındaki tasarıma benzetilmeli, issue örnek ekranlar baz alınabilir.

### EN
- [x] Ana ekran kapanmayacak ve onay kısmı görünecek şekilde bir tasarım olmalı. 
- [x] Kullanıcının konumu ve atamanın konumu arasında bir yol çizilerek ilgili konum ve uzaklığını ön izlemesi görüntülenmeli.
- [x] Açılan pencere içerisinde atamaya ait açıklama, kilometre ve uzaklık bilgisi yer almalıdır.
- [x] Örnek ekranda en üstte bulunan ikonlar olmamalı. Çünkü kullanıcı onayla veya reddet aksiyonlarından birini almak durumunda. Text olarak butonlarda `Approve` ve `Reject` yazmalı.
- [x] Açılır pencerede kullanıcının hiçbir aksiyon almamasına karşın iptal etmek için bir sayaç olmalı, ilgili sayaç 15 saniyelik bir sayaç olmalıdır. 15-10 saniye arası yeşil 10-5 saniye arası sarı ve 5-0 saniye arası kırmızı olarak görünmelidir. Teknik olarak mobil tarafta renk geçişi sağlanabiliyorsa renk geçişi şeklinde de olabilir.
![image](https://github.com/afet-yonetim-sistemi/ays-ui-ux/assets/61833677/f022ca80-bed0-4f2c-82e4-134d6acc1beb)
- [x] Genel ekran tasarımı Kurum tarafındaki tasarıma benzetilmeli, issue örnek ekranlar baz alınabilir.

---

## Örnek Ekranlar;
![preview](https://github.com/afet-yonetim-sistemi/ays-ui-ux/assets/61833677/db6bf482-ebcf-4a20-862b-e7c9eac0dd5d)

---

### Mobil Uygulama Figma Tasarımları;
https://www.figma.com/file/VgGo5zOJXI5Uzq81R4q43K/AYS-Mobil?type=design&node-id=2-1292&mode=design

**Comment by busraselimoglu** [comment]
Taslak Tasarım: https://www.figma.com/file/OarumtKqDTYusOuw1oqIiW/ays-mobil-design-2?type=design&node-id=13%3A221&mode=design&t=ELPThtgoTovp8Slm-1

Genel Tasarım: https://www.figma.com/file/jUl6RLzaN996HsYcZXpdfr/ays-mobil-design-(finished)?type=design&node-id=0%3A1&mode=design&t=d2dHAxMmAuTIyMfn-1
